# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: puzzlehunt.net
description: > # this means to ignore newlines until "baseurl:"
  All things puzzlehunts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.puzzlehunt.net" # the base hostname & protocol for your site

permalink: /:title

# Build settings
markdown: kramdown

twitter_username: betaveros
github_username: betaveros
